name: C/C++ CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    #https://atcoder.jp/contests/APG4b/rules
    - name: compile it
      run: git submodule update && make run
