name: C/C++ CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    #https://atcoder.jp/contests/APG4b/rules
    - name: install ac-lib
      run: git submodule init && git submodule update

    - name: make it
      run: make run
